---
# Install cert-manager for automatic SSL certificate management
# Run: kubectl apply -f cert-manager-setup.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
# cert-manager CRDs and deployment
# This is a simplified version - for production, use the official manifest:
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@shumaspa.cz  # CHANGE THIS to your email
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: traefik

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production server - use only after testing with staging
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@shumaspa.cz  # CHANGE THIS to your email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: traefik
