---
- name: Ensure essential packages are installed
  hosts: pi_cluster
  become: yes
  tasks: 
    - name: Install essential packages and k3s tools
      ansible.builtin.apt:
        name:
          - vim
          - net-tools
          - git
          - htop
          - tmux
          - curl
          - wget
          - jq
          - apt-transport-https
          - dnsutils
          - netcat-traditional
          - traceroute
          - unattended-upgrades
          - fail2ban
          - containerd
          - cgroup-tools
          - apparmor-utils
        state: present
        update_cache: yes
