---
- name: Set up k3s cluster
  hosts: k3s_master
  become: yes
  tasks:
    - name: Install k3s on master node
      shell: |
        curl -sfL https://get.k3s.io | K3S_TOKEN=my_secret_token sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get k3s node token
      shell: sudo cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Display join token (for manual worker setup)
      debug:
        msg: "K3S Join Token: {{ k3s_token.stdout }}"

- name: Set up k3s workers
  hosts: k3s_workers
  become: yes
  vars:
    k3s_master_ip: "10.0.0.100"
    k3s_token: "my_secret_token"
  tasks:
    - name: Install k3s on worker nodes
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      args:
        creates: /usr/local/bin/k3s-agent
