---
- name: Set up web server
  hosts: web_server
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: 0755

    - name: Deploy sample index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>My Raspberry Pi Website</title>
          </head>
          <body>
              <h1>Hello from Raspberry Pi!</h1>
              <p>This is my test website hosted on a Raspberry Pi.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: 0644

    - name: Show web server URL
      debug:
        msg: "Web server available at http://{{ ansible_host }}/"
